services:
  raito-cache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT:-9180}:${PORT:-9180}'
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: ${PORT:-9180}
      HOST: ${HOST:-localhost}
      TTL: ${TTL}
    tty: true
    stdin_open: true
